# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5aeb7364886764df894353d0ce5ca8522d739237e28fc7085a58c2c9358ea3b78b5b29c10f424bbe96b6a29e60427059e789836e8d7a959f2d7e7ba4eeb5810b

test:
  secret_key_base: da2eb887f7045ce81b21a5b0b87614cdabc8a311115148cead28f93fb0393fed0d6db4b6e8b8bbf091a0dbd92f1d0b1120dbc0a539615a0fa39cf52053971414

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
